# Stack configuration for Kubernetes
orchestrator:
  flavor: kubernetes
  settings:
    pod_settings:
      resources:
        requests:
          cpu: "2"
          memory: "4Gi"
        limits:
          cpu: "4"
          memory: "8Gi"

# Docker configuration
settings:
  docker:
    # System requirements for the Docker image
    apt_packages:
      - build-essential
      - git
      - poppler-utils  # For PDF processing
    # Python requirements
    requirements:
      - llama-index>=0.10.0
      - openai>=1.0.0
      - weave
      - wandb
      - torch
      - transformers
      - pdf2image
      - pytesseract
      - pillow

    # Environment variables that will be available in the container
    environment:
      OPENAI_API_KEY: "{{openai_key}}"  # Will be fetched from ZenML secrets
      TEST: "test"