# Stack configuration for Kubernetes
orchestrator:
  flavor: kubernetes
  settings:
    pod_settings:
      resources:
        requests:
          cpu: "1"
          memory: "2Gi"
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: gpu
      #               operator: In
      #               values: ["yes"]
    orchestrator_pod_settings:
      resources:
        requests:
          cpu: "1"
          memory: "1Gi"

# Docker configuration
settings:
  docker:
    requirements: "requirements.txt"
    apt_packages:
      - poppler-utils
    python_package_installer: "uv"
    environment:
      ZENML_ENABLE_RICH_TRACEBACK: false
      WANDB_PROJECT: "zenml_llms"
      HF_HOME: "/tmp/huggingface"
      HF_HUB_CACHE: "/tmp/huggingface"
      HF_TOKEN: "KEY_GOES"
      OPENAI_API_KEY: "KEY_GOES_HERE"
